### ISSUE TITLE
Segmentation fault due to points exceeded

### ISSUE THREAD

**Issue by vtsykun** [wrf-model/WRF#1263]
**To Reproduce**
1. Use compiler and version: 
_gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0_
_WRF V4.1.5 MODEL_
2. Use namelist options, see https://gist.github.com/vtsykun/c396d987844ad2418ecc4e71b74f43df
3. Output is 
```
Timing for main: time 2020-07-03_13:07:00 on domain   2:    0.85588 elapsed seconds
Timing for main: time 2020-07-03_13:08:00 on domain   2:    0.85149 elapsed seconds
Timing for main: time 2020-07-03_13:09:00 on domain   2:    0.85322 elapsed seconds
Timing for main: time 2020-07-03_13:09:00 on domain   1:    4.07912 elapsed seconds
d01 2020-07-03_13:09:00           10  points exceeded cfl=2 in domain d01 at time 2020-07-03_13:09:00 hours
d01 2020-07-03_13:09:00  MAX AT i,j,k:           41          12          18  vert_cfl,w,d(eta)=   4.10377407       14.5423813       5.00418246E-02
d01 2020-07-03_13:09:00            9  points exceeded cfl=2 in domain d01 at time 2020-07-03_13:09:00 hours
d01 2020-07-03_13:09:00  MAX AT i,j,k:           51          43          16  vert_cfl,w,d(eta)=   2.51988530       7.10491991       4.93803620E-02
d01 2020-07-03_13:09:00            5  points exceeded cfl=2 in domain d01 at time 2020-07-03_13:09:00 hours
d01 2020-07-03_13:09:00  MAX AT i,j,k:           51          43          17  vert_cfl,w,d(eta)=   2.48055673       8.97235489       4.99201417E-02
Timing for main: time 2020-07-03_13:10:00 on domain   2:    0.92046 elapsed seconds
Timing for main: time 2020-07-03_13:11:00 on domain   2:    0.85324 elapsed seconds
Timing for main: time 2020-07-03_13:12:00 on domain   2:    0.85288 elapsed seconds
Timing for main: time 2020-07-03_13:12:00 on domain   1:    4.20574 elapsed seconds

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f3142a712da in ???
#1  0x7f3142a70503 in ???
#2  0x7f3141cc6f1f in ???
#3  0x55d71a7c4068 in ???
#4  0x55d71a7c7808 in ???
#5  0x55d71a7ccaec in ???
#6  0x55d719fc5470 in ???
#7  0x55d7197a45d7 in ???
#8  0x55d7192b0ac8 in ???
#9  0x55d719169f96 in ???
#10  0x55d718476cb7 in ???
#11  0x55d718409c19 in ???
#12  0x55d71840956e in ???
#13  0x7f3141ca9b96 in ???
#14  0x55d7184095a9 in ???
#15  0xffffffffffffffff in ???
```

**Expected behavior**
Shouldn't be a SIGSEGV

**Comment by davegill** [comment]
@vtsykun 
Uladzimir,
This is more likely a question that should be sent to the WRF Forum. That is for users to ask questions about model behavior. Please repost this exact question to forum.mmm.ucar.edu. Your first post may take about 24 hours to be accepted. Additionally, include the namelist that you have provided here.

While you are waiting for a response to the forum, reduce your timestep. Try 50 s, instead of 180 s.
