### ISSUE TITLE
Could not open new netcdf file structure 

### ISSUE THREAD

**Issue by Tuanph1970** [wrf-model/WRF#1274]
Dear team,

I have downloaded a WRF Version 4.2.1 and build and tried to run it on Ubuntu system.
During running the program . I have encountered with problem wiith reading file 2019-05-09_11.nc file.
From the command window I saw the bug : The name list;s size í mismatch with input file.

I have attached the log file for this issue.

For more infomation of the issue:

If the size of nc file is about 16 Mb , it can read normally
From file 2019-05-09_11.nc file. the size of file is 24 Mb and the program could not open it

Here is the log content: 

Timing for main: time 2019-05-09_11:21:00 on domain   1:    1.00036 elapsed seconds
d01 2019-05-09_11:21:00            2  points exceeded cfl=2 in domain d01 at time 2019-05-09_11:21:00 hours
d01 2019-05-09_11:21:00  MAX AT i,j,k:           39           9          18  vert_cfl,w,d(eta)=   2.06013870       6.92384338       5.00418246E-02
Timing for main: time 2019-05-09_11:24:00 on domain   1:    1.04821 elapsed seconds
d01 2019-05-09_11:24:00            4  points exceeded cfl=2 in domain d01 at time 2019-05-09_11:24:00 hours
d01 2019-05-09_11:24:00  MAX AT i,j,k:           39           9          19  vert_cfl,w,d(eta)=   2.13596010       6.65227842       4.97004390E-02
d01 2019-05-09_11:24:00            5  points exceeded cfl=2 in domain d01 at time 2019-05-09_11:24:00 hours
d01 2019-05-09_11:24:00  MAX AT i,j,k:           39           9          20  vert_cfl,w,d(eta)=   2.22204113       9.77714252       4.88601625E-02
d01 2019-05-09_11:24:00            6  points exceeded cfl=2 in domain d01 at time 2019-05-09_11:24:00 hours
d01 2019-05-09_11:24:00  MAX AT i,j,k:           39           9          19  vert_cfl,w,d(eta)=   2.23059511       6.66994476       4.97004390E-02
Timing for main: time 2019-05-09_11:27:00 on domain   1:    1.00049 elapsed seconds
d01 2019-05-09_11:27:00            6  points exceeded cfl=2 in domain d01 at time 2019-05-09_11:27:00 hours
d01 2019-05-09_11:27:00  MAX AT i,j,k:           39           9          19  vert_cfl,w,d(eta)=   2.32532549       7.56556749       4.97004390E-02
d01 2019-05-09_11:27:00            7  points exceeded cfl=2 in domain d01 at time 2019-05-09_11:27:00 hours
d01 2019-05-09_11:27:00  MAX AT i,j,k:           39           9          20  vert_cfl,w,d(eta)=   2.40695977       10.2986898       4.88601625E-02
d01 2019-05-09_11:27:00            8  points exceeded cfl=2 in domain d01 at time 2019-05-09_11:27:00 hours
d01 2019-05-09_11:27:00  MAX AT i,j,k:           39           9          19  vert_cfl,w,d(eta)=   2.39766121       6.96662617       4.97004390E-02
Timing for main: time 2019-05-09_11:30:00 on domain   1:    1.04442 elapsed seconds

Timing for main: time 2019-05-09_12:00:00 on domain   1:    0.98216 elapsed seconds
 mediation_integrate.G        1944 DATASET=HISTORY
 mediation_integrate.G        1945  grid%id            1  grid%oid            2
Timing for Writing wrfout_d01_2019-05-09_12:00:00 for domain        1:    0.62352 elapsed seconds
d01 2019-05-09_12:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain        1:    0.03864 elapsed seconds

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F683AB5FE08
#1  0x7F683AB5EF90
#2  0x7F683A2904BF
#3  0x1BDBABC in taugb3.7253 at module_ra_rrtmg_lw.f90:?
#4  0x1BFE2BD in __rrtmg_lw_taumol_MOD_taumol
#5  0x1C222B8 in __rrtmg_lw_rad_MOD_rrtmg_lw
#6  0x1C33641 in __module_ra_rrtmg_lw_MOD_rrtmg_lwrad
#7  0x16799C5 in __module_radiation_driver_MOD_radiation_driver
#8  0x173F7FA in __module_first_rk_step_part1_MOD_first_rk_step_part1
#9  0x127B29F in solve_em_
#10  0x112BA90 in solve_interface_
#11  0x475035 in __module_integrate_MOD_integrate
#12  0x407BF3 in __module_wrf_top_MOD_wrf_run

**Comment by weiwangncar** [comment]
@Tuanph1970 Please post this on the Forum: https://forum.mmm.ucar.edu/phpBB3/. Make sure you describe your issue clearly. Thanks.
