### ISSUE TITLE
When I run /chem/convert_emiss.exe,the error occurs.

### ISSUE THREAD

**Issue by cxyiyh** [wrf-model/WRF#1310]
**Describe the bug**

When I run /chem/convert_emiss.exe,

 Ntasks in X            1 , ntasks in Y            1
WRF-CHEM V4.2 EMISSIONS PREPROCESSOR
 *************************************
 Parent domain
 ids,ide,jds,jde            1         100           1          86
 ims,ime,jms,jme           -4         105          -4          91
 ips,ipe,jps,jpe            1         100           1          86
 *************************************
DYNAMICS OPTION: Eulerian Mass Coordinate
 alloc_space_field: domain            1 ,            1328025904  bytes allocated
 open file wrfinput_d01
med_initialdata_input: calling input_input
 Input data is acceptable to use: wrfinput_d01
 CURRENT DATE          = 2019-07-21_00:00:00
 SIMULATION START DATE = 2019-07-21_00:00:00
Timing for processing wrfinput file (stream 0) for domain        1:    0.98465 elapsed seconds
Max map factor in domain 1 =  1.07. Scale the dt in the model accordingly.
 D01: Time step                              =    90.0000000      (s)
 D01: Grid Distance                          =    30.0000000      (km)
 D01: Grid Distance Ratio dt/dx              =    3.00000000      (s/km)
 D01: Ratio Including Maximum Map Factor     =    3.22043180      (s/km)
 D01: NML defined reasonable_time_step_ratio =    6.00000000
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE LSM RELATED TABLES
 RUCLSMINIT uses MODI-RUC
 INPUT VEGPARM FOR MODI-RUC
 VEGPARM FOR USGS     FOUND          27  CATEGORIES
 Skipping USGS     table
 VEGPARM FOR MODIFIED FOUND          20  CATEGORIES
 Skipping MODIFIED table
 VEGPARM FOR NLCD40   FOUND          40  CATEGORIES
 Skipping NLCD40   table
 VEGPARM FOR USGS-RUC FOUND          28  CATEGORIES
 Skipping USGS-RUC table
 VEGPARM FOR MODI-RUC FOUND          21  CATEGORIES
 Found MODI-RUC table
 Reading MODI-RUC table
 INPUT SOIL TEXTURE CLASSIFICATION = STAS-RUC
 SOIL TEXTURE CLASSIFICATION = STAS-RUC FOUND          19  CATEGORIES

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fdf2c9bb2ed in ???
#1  0x7fdf2c9ba503 in ???
#2  0x7fdf2bbcefcf in ???
#3  0x7fdf2f396800 in ???
#4  0x7fdf2f72951c in ???
#5  0x7fdf2f6fcb29 in ???
#6  0x7fdf2f42d7de in ???
#7  0x7fdf2d4f510e in ???
#8  0x7fdf2d4f4932 in ???
#9  0x7fdf2bbb1b96 in ???
#10  0x7fdf2d4f4969 in ???
#11  0xffffffffffffffff in ???
Segmentation fault (core dumped)

**Comment by weiwangncar** [comment]
@cxyiyh This should be posted on the Forum (https://forum.mmm.ucar.edu/). Thanks.

**Comment by cxyiyh** [comment]
> @cxyiyh This should be posted on the Forum (https://forum.mmm.ucar.edu/). Thanks.

ok, thank you.
